# Generated by Django 2.2.5 on 2019-09-30 03:59

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('file', models.CharField(max_length=50)),
                ('sepal_length', models.FloatField(default=0)),
                ('sepal_width', models.FloatField(default=0)),
                ('petal_length', models.FloatField(default=0)),
                ('petal_width', models.FloatField(default=0)),
                ('species', models.CharField(default='unknown', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
